[package]
name = "concurrent_arena"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.11.2"
bitvec = { version = "0.22.3", features = ["atomic"] }

static_assertions = "1.1.0"
array-init = "2.0.0"
