[package]
name = "concurrent_arena"
version = "0.1.0"
edition = "2018"

[dependencies]
const_fn_assert = "0.1.2"

array-init = "2.0.0"
arrayvec = "0.7.2"

parking_lot = "0.11.2"

[dev-dependencies]
bitvec = "0.20"
rayon = "1.5.1"
